spring.application.name=vlv-blueberry-system

# =========================================================
# ETAPA ACTUAL: SOLO FRONTEND
# =========================================================
# Aun no se configurara MySQL, por eso desactivamos
# temporalmente DataSource y JPA para que la app arranque
# solo con Spring MVC + Thymeleaf + vistas.

spring.thymeleaf.cache=false
server.port=8080